Repository PetalsOnWind/Statistics-and-Econometrics-for-Data-Science, pull requests merged in 2021-04, with the labels that each got.

#159 Changes in Issue #111 .New formulaes are added
  notebooks/Central  Limit Theorem.ipynb
  notebooks/Central Limit Theorem.ipynb
Labels: Level1, gssoc21

#151 Fix issue #96
  notebooks/RFR using GridsearchCV.ipynb
Labels: Level2, gssoc21

#144 Added explanations in multilinear regression notebook #138
  notebooks/Multilinear-Regression.ipynb
Labels: Level1, gssoc21

#122 Added notebook on binary classification :logistic regression
  notebooks/Binary Classification-Logistic Regression.ipynb
Labels: Level3, gssoc21
