Repository PetalsOnWind/Statistics-and-Econometrics-for-Data-Science, pull requests merged in 2021-03, with the labels that each got.

#98 Issue 58
  README.md
  ideas.md
Labels: Level0, gssoc21

#119 Update README.md
  README.md
Labels: Level0, gssoc21

#70 changed intro_numpy,pandas and matplotlib with best example and graph
  data/Breast-Cancer.csv
  notebooks/Decision Tree.ipynb
  notebooks/intro-numpy-pandas-matplotlib.ipynb
Labels: Level1, gssoc21

#94 added detailed notebook on svm
  notebooks/Support_Vector_Machine.ipynb
Labels: Level3, gssoc21

#117 Bayes Theorem NoteBook
  notebooks/Baye's Theorem Notebook.ipynb
Labels: Level3, gssoc21

#109 issue-89 Added the explanation
  notebooks/Correlation.ipynb
Labels: Level2, gssoc21

#124 notebooks/data_summary_breast_cancer.ipynb
  notebooks/data_summary_breast_cancer.ipynb
Labels: Level3, gssoc21

#118 #issue 17 Notebook on Dummy Classifier
  Dummy Classifier Notebook.ipynb
  notebooks/Dummy Classifier Notebook.ipynb
Labels: Level3, gssoc21

#130 Hypothesis Testing Notebook
  images/OneDirectional.png
  images/OnettwoTailed.png
  images/TwoDirectional.png
  notebooks/Hypothesis Testing.ipynb
Labels: Level0, gssoc21

#131 Updated Central Limit Theorem
  WIP/Central Limit Theorem.ipynb
  notebooks/Central Limit Theorem.ipynb
Labels: Level2, gssoc21

#121 Statistical Notebook
  notebooks/Statistical_&_Probability_Notebook_Part_1.ipynb
  notebooks/Statistical_&_Probability_Notebook_Part_2.ipynb
Labels: Level3, gssoc21

#123 Data_Summary #12
  notebooks/Data_Summary_Notebook#12.ipynb
Labels: Level3, gssoc21

#103 Make a notebook on distributions #issue 12
  notebooks/Probability_Distributions_All.ipynb
Labels: Level3, dormant, gssoc21

#129 added few more topics
  ideas.md
Labels: Level0, gssoc21

#107 fix issue #76
  notebooks/Frequency Distribution.ipynb
Labels: Level2, gssoc21

#132 Added 6 topics in ideas.md
  ideas.md
Labels: Level0, gssoc21

#145 added 3 functions in numpy and 1 graph in matplotlib #3
  notebooks/intro-numpy-pandas-matplotlib.ipynb
Labels: Level1, gssoc21
