Repository PetalsOnWind/Statistics-and-Econometrics-for-Data-Science, pull requests merged in 2021-05, with the labels that each got.

#147 Implementation of KNN(K-Nearest-Neighbours) Added
  notebooks/K_Nearest_Neighbours.ipynb
Labels: Level3, gssoc21

#142 Hypothesis Testing Folder added #127
  Hypothesis Testing/Hypo_Testing.ipynb
  Hypothesis Testing/Hypothesis Testing.md
  Hypothesis Testing/PlantGrowth.csv
  Hypothesis Testing/blood_pressure.csv
Labels: Level3, gssoc21

#150 Example for correlation
  notebooks/Correlation with Example/Correlation.ipynb
  notebooks/Correlation with Example/Movie Recommendation using Correlation.ipynb
  notebooks/Correlation with Example/README.md
Labels: Level2, gssoc21

#153 Bias and variance notebook.
  data/food_outlet_data.csv
  notebooks/bias_variance_notebook.ipynb
Labels: Level2, gssoc21

#176 Added differnce between CLT and LNN
  notebooks/LNN.ipynb
Labels: Level0, gssoc21
